#!/bin/bash

function install_icclim() {
    cd /tmp
    git clone https://github.com/cerfacs-globc/icclim && \
        cd icclim && \
        gcc -fPIC -g -c -Wall ./icclim/libC.c -o ./icclim/libC.o && \
        gcc -shared -o ./icclim/libC.so ./icclim/libC.o && \
        python setup.py install
    cd /home/jovyan
}

# =======================================================
# Everything below here is generated by the snapshot job:
# =======================================================
